dist: bionic
language: generic

# Cache the big Vagrant boxes
cache:
  directories:
  - "/home/travis/.vagrant.d/boxes"
  - "/home/travis/build/dls"

install:
# Install libvrt & KVM (see https://github.com/alvistack/ansible-role-virtualbox/blob/master/.travis.yml)
- sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev

# Download Vagrant & Install Vagrant package
- sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
- sudo dpkg -i vagrant_2.2.7_x86_64.deb

# Vagrant correctly installed?
- vagrant --version

# Install vagrant-libvirt Vagrant plugin
- sudo vagrant plugin install vagrant-libvirt

env:
  global: 
    - PROVIDER=libvirt

script:
- sudo sh -x build.sh && ls -lh

before_deploy:
- git tag "$(date +'%Y%m%d')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure: pLNJUIO2209vFWYe6+g01Nk2Am4Wn1jDmhGL4fu2EQ3Rq1fwBjoGNDdL5EP1Go8dHGHLfqsL0iHqGa80nGmDm8QxTHqiW0E6lNBhd+tOdhKDnhiUxlfMux9U3SLxyan2LgN/GG7e0447TjdmdH2Oyfvf/Zu/EJ849JOPxLbKwJsiaOwSGBNqDp3Xns+xbwGaxBLoGiwX9DFtVf6gO2Xpjoq0TAOe+dzrZscbrBy0UvCWFGvCG2Z5KgSqOZ3qm3fSe00tm8QbPE/ICmpO1+rAs0vAvQYrKI6eWVwcjbaqjMs6qC3I9NWBWt64wvNHVwyI5yx057P9uD+nxm6WvxmEhAwIZKfbAjd0M87vi/LnTyKqxyuOwhlbitwexk7M79yD21NsdPZriMjgdtkT0dg2rBYMYywngIy09MTKesjK5q+ZxTkAsZjQU3l/q0gvBWo+oY2BaGehxXOV6EynIciWeXIGYo8SFXL9EUoqiZdZ0D0q03b/BrzwznoV/hGCgzdJQqdB8NpxnHM/TL6v04XnAQLqGEw5EkF8WUj0npj1W3cCHgqZCS6ppOdI4kLrdAvnsCj3iwob6xIVk2M00DlVrhTsHLBZCAUmWgQe2e98HDWD7JZ78LaEhdsUiFmQ/eLq7RL1913HwRnkN9rHfJJHqvBZo8rJL64MccXUNsJQ3lc=
  skip_cleanup: true
  cleanup: false
  overwrite: true
  file_glob: true
  file: "*.7z"
  on:
    repo: pfichtner/armbian-musicbox

